server:
  port: 20001
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

logging:
  level:
    cn.noobbb.coupon: debug

spring:
  cloud:
    stream:
      # 如果你项目里只对接一个中间件，定义 spring.rabbitmq 就可以
      # 当系统要定义多个消息中间件的时候，使用 binders 定义
      binders:
        my-rabbit:
          type: rabbit # 消息中间件类型
          environment: # 连接信息
            spring:
              rabbitmq:
                host: 192.168.31.112
                port: 5672
                username: rabbit
                password: rabbit112
      bindings:
        addCoupon-out-0:
          destination: request-coupon-topic
          content-type: application/json
          binder: my-rabbit
        addCoupon-in-0:
          destination: request-coupon-topic
          content-type: application/json
          # 消费组，同一个组内只能被消费一次
          group: add-coupon-group
          binder: my-rabbit
          error-handler-definition: requestCouponErrorHandler
          consumer:
            # 默认值为 3（首次+2次重试，设置1则禁用重试）
            maxAttempts: 1
            # 重试初始间隔
            backOffInitialInterval: 1000
            # 重试最大间隔
            backOffMaxInterval: 5000
            # 重试乘数（初始间隔*乘数，直到到达最大间隔）
            backOffMultiplier: 2
            # 可重试异常（如果某个异常不想重试可以配置在这里）
#            retryableExceptions:
#              java.lang.IllegalArgumentException: false

        deleteCoupon-out-0:
          destination: delete-coupon-topic
          content-type: text/plain
          binder: my-rabbit
        deleteCoupon-in-0:
          destination: delete-coupon-topic
          content-type: text/plain
          group: delete-coupon-group
          binder: my-rabbit

      rabbit:
        bindings:
#          addCoupon-in-0:
#            consumer:
              #requeue重回队列 重试
#              requeueRejected: true
#              republishToDlq: false
          deleteCoupon-in-0:
            consumer:
              auto-bind-dlq: true


    function:
      definition: addCoupon;deleteCoupon