metadata:
- appName: ''
  dataId: coupon-customer-serv.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: coupon-template-serv.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: coupon-calculation-serv.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: coupon-customer-serv-flow-rules
  group: SENTINEL_GROUP
  type: text
- appName: gateway
  dataId: routes-config.json
  desc: gateway动态路由
  group: DEFAULT_GROUP
  type: json
- appName: gateway
  dataId: coupon-gateway.yml
  desc: gateway
  group: DEFAULT_GROUP
  type: yaml
- appName: redis
  dataId: redis-config.yml
  group: EXT_GROUP
  type: yaml
- appName: rabbitmq
  dataId: rabbitmq-config.yml
  group: EXT_GROUP
  type: text
