server:
  port: 20002
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

logging:
  level:
    cn.noobbb.coupon: debug


management:
  tracing:
    sampling:
      probability: 1.0      # 采样率，默认 0.1
  # 直连 zipkin 的方式：
  zipkin:
    tracing:
      endpoint: http://192.168.31.112:9411/api/v2/spans
