server:
  port: 20000
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

logging:
  level:
    cn.noobbb.coupon: debug

seata:
  application-id: coupon-template-serv
  # 基于 Nacos 服务发现来获取地址信息
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.31.112:8848
      username: nacos
      password: nacos112
      namespace: dev
      group: SEATA_GROUP
      cluster: default
  # 当前应用的事务分组
  tx-service-group: my-seata-server-group
  service:
    vgroup-mapping:
      my-seata-server-group: default