server:
  port: 20000
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

logging:
  level:
    cn.noobbb.coupon: debug

#spring:
#  cloud:
#    sentinel:
#      transport:
#        # sentinel api端口，默认8719
#        port: 8719
#        clientIp: 192.168.31.110
#        # dashboard地址
#        dashboard: 192.168.31.112:8718