server:
  port: 20000
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

logging:
  level:
    cn.noobbb.coupon: debug

spring:
  cloud:
    sentinel:
      transport:
        # sentinel api端口，默认8719
        port: 8719
        # dashboard地址
        dashboard: localhost:8718


management:
  tracing:
    sampling:
      probability: 1.0      # 采样率，默认 0.1
  # 直连 zipkin 的方式：
  zipkin:
    tracing:
      endpoint: http://192.168.31.112:9411/api/v2/spans


