server:
  port: 20099
  error:
    include-message: always

# spring.* 配置已上传 nacos config

# 开启网关的日志打印
logging:
  level:
    reactor:
      netty: INFO
    org.springframework.cloud.gateway: TRACE

# 开放端点
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
